import { createHash } from 'node:crypto'
import { existsSync, mkdirSync, readFileSync, writeFileSync } from 'node:fs'
import { resolve } from 'node:path'

interface EvidenceLock {
  stacksRepository: string
  evidenceRevision: string
  sourceRevision: string
  files: Record<string, string>
}

const root = resolve(import.meta.dir, '..')
const evidenceRoot = resolve(root, 'evidence/stacks')
const lockPath = resolve(evidenceRoot, 'evidence.lock.json')
const pagePath = resolve(root, 'docs/reference/source-evidence.md')
const sourceFiles = [
  'protocol/evidence/source-manifest.json',
  'protocol/evidence/drivers.json',
  'protocol/evidence/desktop-support.json',
  'protocol/suite.lock.json',
]

function hash(data: Buffer | string): string {
  return `sha256:${createHash('sha256').update(data).digest('hex')}`
}

function gitRevision(repository: string): string {
  const result = Bun.spawnSync(['git', '-C', repository, 'rev-parse', 'HEAD'])
  if (result.exitCode !== 0) throw new Error('Could not resolve the Stacks evidence revision')
  return result.stdout.toString().trim()
}

function renderPage(lock: EvidenceLock): string {
  const source = JSON.parse(readFileSync(resolve(evidenceRoot, 'source-manifest.json'), 'utf8'))
  const drivers = JSON.parse(readFileSync(resolve(evidenceRoot, 'drivers.json'), 'utf8'))
  const desktop = JSON.parse(readFileSync(resolve(evidenceRoot, 'desktop-support.json'), 'utf8'))
  const suite = JSON.parse(readFileSync(resolve(evidenceRoot, 'suite.lock.json'), 'utf8'))
  const categories = Object.entries(source.inventory.categories as Record<string, { files: number, bytes: number }>)
    .map(([name, value]) => `| ${name} | ${value.files.toLocaleString('en-US')} | ${value.bytes.toLocaleString('en-US')} |`).join('\n')
  const statuses = ['supported', 'partial', 'experimental', 'unsupported'].map((status) => {
    const count = drivers.drivers.filter((driver: { status: string }) => driver.status === status).length
    return `| ${status} | ${count} |`
  }).join('\n')
  const selectedPackages = source.packages.filter((pkg: { name: string }) => ['stacks', '@stacksjs/config', '@stacksjs/env', '@stacksjs/desktop'].includes(pkg.name))
    .map((pkg: { name: string, version: string, path: string }) => `| \`${pkg.name}\` | \`${pkg.version}\` | \`${pkg.path}\` |`).join('\n')

  return `---
title: Reproducible source evidence
description: Generated Stacks.js source, protocol, driver, and desktop evidence pinned to immutable revisions.
---
# Reproducible source evidence

This page is generated by \`bun run evidence:sync\`. Its inputs are copied from
the Stacks repository and verified byte-for-byte against
\`evidence/stacks/evidence.lock.json\`. It reports inventory, not quality or
conformance.

| Evidence | Immutable revision |
| --- | --- |
| Evidence-producing Stacks commit | [\`${lock.evidenceRevision}\`](https://github.com/stacksjs/stacks/tree/${lock.evidenceRevision}) |
| Audited Stacks source tree | [\`${source.sourceRevision}\`](https://github.com/stacksjs/stacks/tree/${source.sourceRevision}) |
| RFC repository | [\`${suite.rfcsRevision}\`](https://github.com/stacksjs/rfcs/tree/${suite.rfcsRevision}) |
| Source digest | \`${source.sourceDigest}\` |

The source manifest classifies Stacks as a **reference implementation** with an
**unverified** protocol claim. No package count or unit test upgrades that claim.

## Package provenance

| Package | Version | Manifest path |
| --- | --- | --- |
${selectedPackages}

The root workspace and published framework package intentionally remain separate
rows. Consumers must identify an exact source revision and package manifest rather
than treating one repository-wide version string as authoritative.

## Classified inventory

| Category | Files | Bytes |
| --- | ---: | ---: |
${categories}

Total: ${source.inventory.totalFiles.toLocaleString('en-US')} files and
${source.inventory.totalBytes.toLocaleString('en-US')} bytes across
${source.packages.length} versioned package manifests. Generated, test, docs,
configuration, vendored protocol, and source files are deliberately separate.

## Driver evidence

The runtime-linked registry contains ${drivers.drivers.length} individual records
across database, queue, cache, storage, mail, realtime, and deployment.

| Status | Drivers |
| --- | ---: |
${statuses}

“Supported” requires checked-in automated evidence. “Partial” lacks live-service
or parity evidence, “experimental” lacks a compatibility commitment or complete
matrix, and “unsupported” must fail loudly. Service versions and CI-run URLs belong
in per-run conformance reports rather than this static inventory.

## Environment encryption

The pinned source writes the experimental \`encrypted:v2\` envelope proposed in
[RFC 0005](https://github.com/stacksjs/rfcs/blob/${suite.rfcsRevision}/rfcs/0005-versioned-environment-encryption.md):
ephemeral-static X25519, HKDF-SHA-256, and AES-256-GCM with authenticated
metadata. The legacy format is read only for migration. Broad production
recommendation remains blocked on
[RFC ratification](https://github.com/stacksjs/rfcs/issues/6) and
[independent review](https://github.com/stacksjs/stacks/issues/2061).

## Craft desktop evidence

The generated Craft matrix has **${desktop.stableTargets} stable targets**.
macOS arm64/x64, Linux x64, and Windows x64 are experimental unpackaged bundles;
unlisted targets are unsupported. Stable publication is mechanically blocked
until platform signing/notarization and retained native install, launch, update,
rollback, and uninstall evidence exist. See
[#2059](https://github.com/stacksjs/stacks/issues/2059),
[#2062](https://github.com/stacksjs/stacks/issues/2062), and
[#2063](https://github.com/stacksjs/stacks/issues/2063).

## Refresh procedure

1. Check out the intended Stacks revision with its dependencies available.
2. In Stacks, run all protocol evidence checks and intentionally refresh the source manifest for the selected immutable revision.
3. In this repository, run \`bun run evidence:sync -- --source ../stacks\`.
4. Review the lock, generated page, capability changes, and limitation changes.
5. Run \`bun run evidence:check\` and \`bun run build\` before committing.
`
}

function writeEvidence(sourceRepository: string): void {
  mkdirSync(evidenceRoot, { recursive: true })
  const files: Record<string, string> = {}
  for (const sourcePath of sourceFiles) {
    const contents = readFileSync(resolve(sourceRepository, sourcePath))
    const targetName = sourcePath.endsWith('suite.lock.json') ? 'suite.lock.json' : sourcePath.split('/').pop()!
    writeFileSync(resolve(evidenceRoot, targetName), contents)
    files[targetName] = hash(contents)
  }
  const source = JSON.parse(readFileSync(resolve(evidenceRoot, 'source-manifest.json'), 'utf8'))
  const lock: EvidenceLock = {
    stacksRepository: 'https://github.com/stacksjs/stacks',
    evidenceRevision: gitRevision(sourceRepository),
    sourceRevision: source.sourceRevision,
    files,
  }
  writeFileSync(lockPath, `${JSON.stringify(lock, null, 2)}\n`)
  writeFileSync(pagePath, renderPage(lock))
  console.log(`Pinned Stacks evidence ${lock.evidenceRevision} for source ${lock.sourceRevision}`)
}

function checkEvidence(): void {
  if (!existsSync(lockPath)) throw new Error('Stacks evidence lock is missing')
  const lock = JSON.parse(readFileSync(lockPath, 'utf8')) as EvidenceLock
  const errors = Object.entries(lock.files).flatMap(([name, expected]) => {
    const path = resolve(evidenceRoot, name)
    if (!existsSync(path)) return [`missing: ${name}`]
    return hash(readFileSync(path)) === expected ? [] : [`modified: ${name}`]
  })
  if (readFileSync(pagePath, 'utf8') !== renderPage(lock)) errors.push('stale: docs/reference/source-evidence.md')
  if (errors.length > 0) throw new Error(`Stacks evidence check failed:\n${errors.join('\n')}`)
  console.log(`Stacks evidence matches ${lock.evidenceRevision}`)
}

if (process.argv.includes('--write')) {
  const index = process.argv.indexOf('--source')
  const source = resolve(index === -1 ? resolve(root, '../stacks') : process.argv[index + 1] || '')
  writeEvidence(source)
}
else if (process.argv.includes('--check')) checkEvidence()
else {
  console.error('usage: bun scripts/sync-stacks-evidence.ts --write [--source ../stacks] | --check')
  process.exit(2)
}
